#!/usr/bin/env bash
# SCRIPT: Prepares the necessary input files for the R enrichment analysis.

set -euo pipefail

## CONFIGURATION ##
WORKSPACE_DIR="/data/training2/analisis_TFM_Bulida_Precoz/10_functional_annotation"
# This is the file generated by your script 4_annotate_with_GO.sh
ANNOTATION_FILE="${WORKSPACE_DIR}/blast_annotation/exploded_go_terms.tsv"

# Output file: a two-column map of GENE_ID -> GO_TERM
GENE2GO_MAP_FILE="${WORKSPACE_DIR}/gene2go_background.tsv"

echo "--- Preparing gene-to-GO mapping file ---"

# We use awk to format the input into the two-column format required by clusterProfiler
# We take the first column (Gene ID) and the third column (GO ID)
awk 'BEGIN{FS="\t"; OFS="\t"} NR>1 {print $1, $3}' "${ANNOTATION_FILE}" > "${GENE2GO_MAP_FILE}"

echo "Preparation complete. The following files are ready for R:"
echo "1. Gene list of interest: ${WORKSPACE_DIR}/final_gene_list.txt"
echo "2. Background universe map: ${GENE2GO_MAP_FILE}"